### ISSUE TITLE
REST Login and Consent

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/whisper#13]
1. Adapt Login and Consent endpoints to work as REST apis:
  1.1. delegate redirection responsibility to front-end, by returning hydra's redirect_uri
  1.2 appropriately return error messages to be shown to the user
2. Adapt Login and Consent JS to work with the new REST apis 
  2.1. redirecting when appropriate
  2.2. improving error handling and notification

**Comment by claudiosegala** [comment]
This issue can be closed right?

**Comment by abilioesteves** [comment]
Yes. It should've been mentioned in the approved Pull Request. Thanks!
