### ISSUE TITLE
Add Forgot My Password option

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/whisper#18]
After #5 is done, users of whisper would benefit a lot from a "forgot my password" link.

The suggested flow is a simple email sent to the registered email address with a recovery link to the correct page.

**Comment by claudiosegala** [comment]
@abilioesteves this issue is basically complete under branch issue#18 but it needs to use the next version of whisper-client. So when that version is complete, I will send the PR that fix this issue.
