### ISSUE TITLE
Update User Credential Bug

### ISSUE THREAD

**Issue by claudiosegala** [labbsr0x/whisper#33]
@abilioesteves in whisper we have this function bellow that updates the user email. Should we let the user update the email?

https://github.com/labbsr0x/whisper/blob/c940534789f77d04116d59b8ec5d98a286a7e1c0/db/usercredentials.go#L113-L132

Another thing is that I believe that the function name is not mnemonic. Since it will create another salt regardless of what you are trying to update, meaning that this function is intended to update the password. 

PS: I did not see that it would update the salt every time and it gave me a headache in #5.

**Comment by abilioesteves** [comment]
> @abilioesteves in whisper we have this function bellow that updates the user email. Should we let the user update the email?

Yes, we should. The username, though, I think is not wise. The email confirmation flow should be in place after an update to the user's email.

> Another thing is that I believe that the function name is not mnemonic. Since it will create another salt regardless of what you are trying to update, meaning that this function is intended to update the password.

This function is intended to update user credential information. That includes passwords. We could change it to identify if the password has changed, and only then calculate a new salt.

**Comment by abilioesteves** [comment]
@claudiosegala, just noticed that the `UpdateUserCredential` does not invalidate the email if it changes its value. Please, could you fix that in this issue? 

In other words, we need to verify the new provided email with the same validation logic we use at registration.

**Comment by claudiosegala** [comment]
@abilioesteves it would be interesting to log out the user if we change his email.

**Comment by abilioesteves** [comment]
@claudiosegala, we should implement following Hydra's guidelines: https://www.ory.sh/docs/hydra/oauth2#logout

**Comment by abilioesteves** [comment]
@claudiosegala another option is to just revoke the login sessions: https://www.ory.sh/docs/hydra/oauth2#revoking-consent-and-login-sessions

**Comment by claudiosegala** [comment]
@abilioesteves should I create another issue for implementing this logout?

**Comment by abilioesteves** [comment]
Yes, please.

**Comment by claudiosegala** [comment]
@abilioesteves should I merge this function with the new version of the update function?

https://github.com/labbsr0x/whisper/blob/369eed1e2185bcc4ac021cb589dd31692642c970/db/usercredentials.go#L99-L108

**Comment by abilioesteves** [comment]
No need to merge them... This way, the Validation logic can evolve on it's own.

**Comment by claudiosegala** [comment]
> @claudiosegala another option is to just revoke the login sessions: https://www.ory.sh/docs/hydra/oauth2#revoking-consent-and-login-sessions

@abilioesteves the documentation says:

> This endpoint is not compatible with OpenID Connect Front-/Backchannel logout and does not revoke any tokens.

Since we work with OpenID, should I worry?
